<?php

namespace Modules\Office\Documents\Application;

use Modules\Office\Core\Contracts\OfficePageProvider;
use Modules\Office\Core\Support\PageBuilder;

class DocumentsPageProvider implements OfficePageProvider
{
    public function pages(): array
    {
        $documents = [
            [
                'id' => '101',
                'title' => '4670442923 هيه مومنه.pdf',
                'originalName' => '4670442923.pdf',
                'category' => 'العقود',
                'visibility' => 'للعميل',
                'client' => 'Mohamed Sa’ed',
                'type' => 'عميل',
                'format' => 'Pdf',
                'extension' => 'pdf',
                'size' => '1.2 MB',
                'owner' => 'أ. خالد',
                'uploadedAt' => '16 مايو 2026',
                'createdAt' => '16 مايو 2026',
                'updatedAt' => '16 مايو 2026',
                'notes' => 'نسخة موقعة من العميل.',
                'tags' => 'عقد,عميل',
                'relatedBucket' => 'العملاء',
                'relatedLabel' => 'عميل: Mohamed Sa’ed',
                'previewable' => 'yes',
            ],
            [
                'id' => '102',
                'title' => 'لائحة استئناف - CASE-2026-001',
                'originalName' => 'appeal-case-2026-001.pdf',
                'category' => 'مستند قضائي',
                'visibility' => 'داخلي',
                'client' => 'شركة الرؤية',
                'type' => 'قضية',
                'format' => 'Pdf',
                'extension' => 'pdf',
                'size' => '2.6 MB',
                'owner' => 'أ. ليلى',
                'uploadedAt' => '15 مايو 2026',
                'createdAt' => '15 مايو 2026',
                'updatedAt' => '15 مايو 2026',
                'notes' => 'مستند مرافعة للاستئناف.',
                'tags' => 'قضية,استئناف',
                'relatedBucket' => 'القضايا',
                'relatedLabel' => 'قضية: CASE-2026-001',
                'previewable' => 'yes',
            ],
            [
                'id' => '103',
                'title' => 'تفويض خدمة - REQ-014',
                'originalName' => 'service-authorization-014.pdf',
                'category' => 'تفويضات',
                'visibility' => 'خاص',
                'client' => 'Fatmahf',
                'type' => 'خدمة',
                'format' => 'Pdf',
                'extension' => 'pdf',
                'size' => '980 KB',
                'owner' => 'أ. فواز',
                'uploadedAt' => '14 مايو 2026',
                'createdAt' => '14 مايو 2026',
                'updatedAt' => '14 مايو 2026',
                'notes' => 'تفويض عملية خدمة.',
                'tags' => 'خدمة,تفويض',
                'relatedBucket' => 'الخدمات',
                'relatedLabel' => 'طلب: REQ-014',
                'previewable' => 'yes',
            ],
            [
                'id' => '104',
                'title' => 'سياسة تصنيف المستندات',
                'originalName' => 'document-classification-policy.docx',
                'category' => 'سياسات',
                'visibility' => 'داخلي',
                'client' => '-',
                'type' => 'أخرى',
                'format' => 'Doc',
                'extension' => 'docx',
                'size' => '420 KB',
                'owner' => 'أ. فواز',
                'uploadedAt' => '11 مايو 2026',
                'createdAt' => '11 مايو 2026',
                'updatedAt' => '11 مايو 2026',
                'notes' => 'دليل داخلي للتصنيفات.',
                'tags' => 'تصنيفات,سياسات',
                'relatedBucket' => 'التصنيفات',
                'relatedLabel' => 'فئة: سياسات',
                'previewable' => 'no',
            ],
            [
                'id' => '105',
                'title' => 'مرفق غير مصنف 2026-05',
                'originalName' => 'unknown-2026-05.zip',
                'category' => 'غير مصنف',
                'visibility' => 'خاص',
                'client' => '-',
                'type' => 'أخرى',
                'format' => 'Other',
                'extension' => 'zip',
                'size' => '8.5 MB',
                'owner' => 'النظام',
                'uploadedAt' => '10 مايو 2026',
                'createdAt' => '10 مايو 2026',
                'updatedAt' => '10 مايو 2026',
                'notes' => '',
                'tags' => '',
                'relatedBucket' => 'أخرى',
                'relatedLabel' => '-',
                'previewable' => 'no',
            ],
        ];

        $bucketCounts = [
            'العملاء' => count(array_filter($documents, fn (array $row): bool => $row['relatedBucket'] === 'العملاء')),
            'القضايا' => count(array_filter($documents, fn (array $row): bool => $row['relatedBucket'] === 'القضايا')),
            'الخدمات' => count(array_filter($documents, fn (array $row): bool => $row['relatedBucket'] === 'الخدمات')),
            'التصنيفات' => count(array_filter($documents, fn (array $row): bool => $row['relatedBucket'] === 'التصنيفات')),
            'أخرى' => count(array_filter($documents, fn (array $row): bool => $row['relatedBucket'] === 'أخرى')),
        ];

        $archiveFolders = [
            ['name' => 'العملاء', 'count' => (string) $bucketCounts['العملاء']],
            ['name' => 'القضايا', 'count' => (string) $bucketCounts['القضايا']],
            ['name' => 'الخدمات', 'count' => (string) $bucketCounts['الخدمات']],
            ['name' => 'التصنيفات', 'count' => (string) $bucketCounts['التصنيفات']],
            ['name' => 'أخرى', 'count' => (string) $bucketCounts['أخرى']],
        ];

        $archiveRecent = array_map(
            fn (array $row): array => [
                'id' => $row['id'],
                'title' => $row['title'],
                'category' => $row['category'],
                'format' => $row['format'],
                'size' => $row['size'],
                'visibility' => $row['visibility'],
                'related' => $row['relatedBucket'],
                'owner' => $row['owner'],
                'updatedAt' => $row['uploadedAt'],
            ],
            $documents,
        );

        return [
            PageBuilder::archive(
                '/office/archive',
                'الأرشيف',
                'عرض بصري للأرشيف مع مجلدات رئيسية وآخر الملفات المؤرشفة.',
                $archiveFolders,
                $archiveRecent,
            ),
            PageBuilder::archive(
                '/office/archive/clients',
                'الأرشيف',
                'عرض بصري للأرشيف مع مجلدات رئيسية وآخر الملفات المؤرشفة.',
                $archiveFolders,
                $archiveRecent,
            ),
            PageBuilder::archive(
                '/office/archive/cases',
                'الأرشيف',
                'عرض بصري للأرشيف مع مجلدات رئيسية وآخر الملفات المؤرشفة.',
                $archiveFolders,
                $archiveRecent,
            ),
            PageBuilder::archive(
                '/office/archive/services',
                'الأرشيف',
                'عرض بصري للأرشيف مع مجلدات رئيسية وآخر الملفات المؤرشفة.',
                $archiveFolders,
                $archiveRecent,
            ),
            PageBuilder::archive(
                '/office/archive/categories',
                'الأرشيف',
                'عرض بصري للأرشيف مع مجلدات رئيسية وآخر الملفات المؤرشفة.',
                $archiveFolders,
                $archiveRecent,
            ),
            PageBuilder::archive(
                '/office/archive/other',
                'الأرشيف',
                'عرض بصري للأرشيف مع مجلدات رئيسية وآخر الملفات المؤرشفة.',
                $archiveFolders,
                $archiveRecent,
            ),
            PageBuilder::table(
                '/office/documents',
                'المستندات',
                'إدارة المستندات مع البحث، الفلاتر، الرؤية، والحذف الجماعي.',
                ['بحث', 'نوع الارتباط', 'الفئة', 'الخصوصية', 'العميل'],
                ['الإجراءات', 'حذف المحدد', 'تطبيق التصفيات', 'تطبيق الأعمدة'],
                PageBuilder::columns([
                    ['key' => 'id', 'label' => 'ID'],
                    ['key' => 'previewable', 'label' => 'معاينة'],
                    ['key' => 'title', 'label' => 'العنوان'],
                    ['key' => 'category', 'label' => 'الفئة'],
                    ['key' => 'visibility', 'label' => 'الخصوصية'],
                    ['key' => 'client', 'label' => 'العميل'],
                    ['key' => 'type', 'label' => 'النوع'],
                    ['key' => 'uploadedAt', 'label' => 'تاريخ الرفع'],
                    ['key' => 'owner', 'label' => 'تم الرفع بواسطة'],
                    ['key' => 'format', 'label' => 'الصيغة'],
                    ['key' => 'extension', 'label' => 'الامتداد'],
                    ['key' => 'size', 'label' => 'الحجم'],
                    ['key' => 'tags', 'label' => 'الوسوم'],
                    ['key' => 'notes', 'label' => 'ملاحظات'],
                    ['key' => 'originalName', 'label' => 'الاسم الأصلي'],
                    ['key' => 'createdAt', 'label' => 'تاريخ الإنشاء'],
                    ['key' => 'updatedAt', 'label' => 'تاريخ التحديث'],
                    ['key' => 'relatedLabel', 'label' => 'الارتباطات'],
                ]),
                $documents,
            ),
        ];
    }
}
